"use client";
import { useCallback, useEffect, useRef, useState } from "react";
const labels = { pending_review: "Pending review", contacted: "Contacted", accepted: "Accepted", rejected: "Rejected", cancelled: "Cancelled" };
export default function OperatorInbox() {
  const [data, setData] = useState(null), [error, setError] = useState(""), [filters, setFilters] = useState({ status: "", service: "", fulfillment: "" }), [page, setPage] = useState(1);
  const [detail, setDetail] = useState(null), [detailError, setDetailError] = useState(""); const dialog = useRef(null);
  const expired = (response) => { if (response.status === 401) { location.replace("/operator/login"); return true; } return false; };
  const load = useCallback(async () => { setError(""); setData(null); try { const q = new URLSearchParams(Object.entries(filters).filter(([,v]) => v)); q.set("page", String(page)); const response = await fetch(`/operator/api/requests?${q}`); if (expired(response)) return; if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError("The request inbox could not be loaded."); } }, [filters, page]);
  // Queue retrieval intentionally resets stale rows before the asynchronous fetch.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  async function reveal(id) { setDetailError(""); try { const response = await fetch(`/operator/api/requests/${id}`); if (expired(response)) return; if (!response.ok) throw new Error(); setDetail(await response.json()); dialog.current?.showModal(); } catch { setDetailError("Sensitive details could not be loaded."); } }
  async function transition(newStatus) { let reason = "";
    if (!confirm(`Confirm status change to ${labels[newStatus]}?`)) return;
    reason = prompt("Required operator note/reason (3–500 characters):")?.trim() || ""; if (reason.length < 3 || reason.length > 500) { setDetailError("A 3–500 character reason is required."); return; }
    setDetailError(""); const response = await fetch(`/operator/api/requests/${detail.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentStatus: detail.status, version: detail.version, newStatus, reason }) });
    if (expired(response)) return; if (!response.ok) { setDetailError(response.status === 409 ? "This request changed. Reload and try again." : "That status transition is not allowed."); return; }
    const changed = await response.json(); setDetail({ ...detail, status: changed.status, version: changed.version }); await load();
  }
  async function logout() { setError(""); try { const response = await fetch("/operator/api/logout", { method: "POST" }); if (!response.ok) throw new Error(); location.replace("/operator/login"); } catch { setError("Sign out could not be confirmed. You remain signed in; try again."); } }
  const actions = detail?.status === "pending_review" ? ["contacted", "cancelled"] : detail?.status === "contacted" ? ["accepted", "rejected", "cancelled"] : [];
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 md:p-8"><div className="mx-auto max-w-6xl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold text-emerald-700">REGO PILOT OPERATIONS</p><h1 className="text-3xl font-black">Customer request inbox</h1><p className="text-sm text-slate-600">Requests are pending review—not bookings. No payment or provider assignment.</p></div><button onClick={logout} className="rounded-lg border bg-white px-4 py-2 font-semibold">Sign out</button></header>
    <section aria-label="Queue filters" className="my-6 grid gap-3 rounded-xl bg-white p-4 md:grid-cols-3"><label>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className="mt-1 block w-full rounded border p-2"><option value="">All statuses</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Service ID<input value={filters.service} onChange={e=>setFilters({...filters,service:e.target.value})} className="mt-1 block w-full rounded border p-2" /></label><label>Fulfillment ID<input value={filters.fulfillment} onChange={e=>setFilters({...filters,fulfillment:e.target.value})} className="mt-1 block w-full rounded border p-2" /></label></section>
    {!data && !error && <p role="status">Loading requests…</p>}{error && <p role="alert" className="text-red-700">{error} <button onClick={load} className="underline">Retry</button></p>}{detailError && !detail && <p role="alert">{detailError}</p>}
    {data?.items.length === 0 && <p className="rounded-xl bg-white p-8 text-center">No requests match these filters.</p>}
    <ul className="grid gap-3">{data?.items.map(item=><li key={item.id} className="rounded-xl bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono font-bold">{item.reference}</p><p className="text-lg font-bold">{item.service.name} · {item.fulfillment.label}</p><p>{item.hasSchedulePreference ? "View details" : "No schedule preference"} · {item.quoteStatus}</p><p className="text-sm text-slate-600">{item.contact || "No contact"} · {item.address}{item.vinSuffix && ` · VIN ending ${item.vinSuffix}`}</p><time className="text-xs text-slate-500" dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time></div><div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-bold">{labels[item.status]}</span><button onClick={()=>reveal(item.id)} className="ml-3 rounded-lg bg-slate-900 px-4 py-2 font-bold text-white">Reveal details</button></div></div></li>)}</ul>
    {data && <nav aria-label="Queue pages" className="my-4 flex items-center justify-end gap-3"><button disabled={page <= 1} onClick={()=>setPage(page-1)} className="rounded border bg-white px-4 py-2 disabled:opacity-50">Previous</button><span>Page {page}</span><button disabled={page * data.pageSize >= data.total} onClick={()=>setPage(page+1)} className="rounded border bg-white px-4 py-2 disabled:opacity-50">Next</button></nav>}
    <dialog ref={dialog} aria-labelledby="detail-title" onClose={()=>setDetail(null)} className="w-[min(94vw,42rem)] rounded-2xl p-0 backdrop:bg-black/60"><div className="p-6">{detail && <><h2 id="detail-title" className="text-2xl font-black">Request {detail.reference}</h2><div role="note" className="my-4 rounded-lg border-2 border-red-600 bg-red-50 p-3 font-bold text-red-900">Sensitive customer data revealed. Use only to fulfill this request.</div><dl className="grid gap-2"><div><dt className="font-bold">Contact</dt><dd>{detail.customer.name} · {detail.customer.email || detail.customer.phone}</dd></div><div><dt className="font-bold">Exact address</dt><dd>{detail.location.address}</dd></div><div><dt className="font-bold">Location notes</dt><dd>{detail.location.notes || "None"}</dd></div><div><dt className="font-bold">Status</dt><dd>{labels[detail.status]}</dd></div></dl>{detailError && <p role="alert" className="mt-3 text-red-700">{detailError}</p>}<div className="mt-5 flex flex-wrap gap-2">{actions.map(action=><button key={action} onClick={()=>transition(action)} className="rounded bg-emerald-700 px-4 py-2 font-bold text-white">Mark {labels[action]}</button>)}</div></>}<form method="dialog"><button className="mt-5 rounded border px-4 py-2">Close</button></form></div></dialog>
  </div></main>;
}
